### PR TITLE
Improve identifying analytics

### PR DESCRIPTION
**Pull request by xsyann**
As recommended by Segment documentation, identify is now also called at log-in.
(https://segment.com/docs/connections/spec/identify/)

Reserved and custom traits have now a more distinct separation as they are handled a bit differently by Segment ($ prefix or case handling for instance).
https://segment.com/docs/connections/spec/identify/#traits

### CODE REVIEW

**Comment by Donorhan** [comment]
Awesome, thank you very much!

**Comment by xsyann** [comment]
I hope the renaming to reserved traits like `sign_up_date` -> `created_at` doesn't break your current analytics.

**Comment by Donorhan** [comment]
@xsyann That's okay, it's better to make the change now than later. On the other hand I see that we send the email address, are you ok with that in terms of confidentiality? We used to avoid putting this data up

**Comment by xsyann** [comment]
@Donorhan It should be okay on our side, we will confirm this with our lawyer.
However, from what I see, the email was already provided in the `login_email_address` property.

Do you want a PR with a setting flag like:
```json
"segmentAnalyticsSettings": {
    "enable": false,
    "workspace": "",
    "writeKey": "",
    "anonymous": true
  }
```

Where email and name is replaced by userId when anonymous is enabled?

**Comment by Donorhan** [comment]
You are right, in fact in the previous code there was a bug so a lot of data was not sent back because of this line:
`analyticsInstance.identify({ userId: user._id, traits: { ...userData, ...newUserDefaultData }, context });`

I think we can leave it like that for now, I saw that we can disable the transmission of some fields from segment too 🙂

**Pull request merged**
