### PR TITLE
Report users

### PR DESCRIPTION
**Pull request by Flowtter**
Add a report option.
Useful to report an user or a message.
Available in:
- profile
- radial menu
- messages

[video](https://user-images.githubusercontent.com/34689945/195100347-dd9008cd-41ba-4a0b-aa10-3735550c1311.mp4)

### CODE REVIEW

**Comment by Donorhan** [comment]
This is a great idea for open levels, thanks! Would it be possible to move this to a module? The "modules" folder, I think you can put the css, hbs and JS in there. For the integration in the radial menu and other interfaces I could do it in a second time if you are not comfortable with that

**Comment by Flowtter** [comment]
ACK, I'll have a look next week probably !
Thanks for the fast feedback.

**Comment by alimtunc** [comment]
> For the integration in the radial menu and other interfaces I could do it in a second time if you are not comfortable with that

What do you mean ? I don't see anything wrong with the implement, did I missed something ? 🙂

**Comment by Donorhan** [comment]
@alimtunc Sorry, maybe I misspoke. Instead of directly editing the `radial-menu.js` file to add the option, you can do something like I did in the `textual-communication-tools.js`: 
```
 registerModules(
    [
      { id: 'report', icon: '🚨️', order: 4, label: 'Report', shortcut: 53, closeMenu: true, scope: 'other' },
    ],
    moduleType.RADIAL_MENU,
  );
```

And add a listener on the radial menu in the `report.js` file with:
```
window.addEventListener(eventTypes.onMenuOptionSelected, onMenuOptionSelected);
```

The advantage of this is that the core is not aware of the existence of your module and you can remove the module without affecting the simulation.

**Review by Donorhan — APPROVED** [review]
Thanks you 🙏🏻

**Pull request merged**
