### PR TITLE
Make the developer onboarding simpler and platform-agnostic

### PR DESCRIPTION
**Pull request by ramnes**
The scripts in the repository give the impression that running the project is quite complicated, whereas running a Meteor app is actually a simple 3 steps process:

* Install system dependencies if any
* Run `meteor npm install`
* Run `meteor`

Also, the current scripts do quite a bunch of extra stuff that's not strictly necessary, and are quite platform dependent.

Let's KISS by removing the scripts and exposing the real commands instead.

### CODE REVIEW

**Comment by DblK** [comment]
The other scripts are used to not have to read the documentation. Most of the time, user or dev do not read it.
Since inside the company we have the same material, that is why the scripts were done (to avoid reading doc for first of your step).

I concur to you about KISS. Can you add the information that we need to have NodeJS and the right version?
I know it's written in Meteor doc, but if someone wants to launch it, reading 2 documentations is not KISS ;)

**Comment by DblK** [comment]
If you are on Windows, you need to have `npm` installed as per documentation.
If we remove our macOS specific scripts then it should work (or at least give enough explanation) for all 3 OS.

**Comment by ramnes** [comment]
Alright, I think we could have skipped this but let's move on, I've added a note about it. :)

**Comment by ramnes** [comment]
Anything else I can do? :)

**Comment by DblK** [comment]
Everything seems to be fine except the `docker-compose` (not prod) which still reference port `9000` for the app.
Maybe check that the `docker-compose` for dev is still working.

Once that is done, it sounds great to me merged!

**Comment by DblK** [comment]
Thanks for your reply. Since you modified the port to go back to the default one and updated the doc accordingly, I guess it would make sense if you launch it via `docker-compose` or with meteor that the address is the same.

So, please, can you make this last change before we merge it?

**Comment by DblK** [comment]
Sorry, one last thing. I just fixed an issue with the `settings-dev.json` and so I added `http://localhost:9000`.
Can you retrieve the last commit and change it in your PR.
After that I will merge it, I promise! ^^

**Comment by ramnes** [comment]
done

**Pull request merged**
