### PR TITLE
1 - Developer can disabled tchat tools in settings

### PR DESCRIPTION
**Pull request by YglesEyes**
Add in settings

```json
{
  "public": {
    "disabledFeatures": ["textualCommunicationTools"]
  }
}
```

### CODE REVIEW

**Comment by ramnes** [comment]
#139 doesn't work for what you want to achieve?

**Comment by YglesEyes** [comment]
The goal is to have a more global restriction for the server and not only for a team, for the moment it seems easier to use flag instead of rework the code to have optional modules.

**Comment by ramnes** [comment]
At the very least we should use the same format and module names, i.e. here we should replicate how `guests` is structured:

```
{
  "features": {
    "useMessaging": false
  }
}
```

rather than 

```
{
  "disabledFeatures": ["textualCommunicationTools"]
}
```

or it will be a nightmare to streamline later. :(

**Comment by YglesEyes** [comment]
Like it, it is more generic and configurable, i don't have time yet but I will implement it ASAP

**Pull request merged**
