### PR TITLE
Use event.KeyCode on keyboard to trigger all layout keyboards

### PR DESCRIPTION
**Pull request by alimtunc**
Handle other layout keyboards, there is only one thing left. Determine if it's Qwerty or Azerty.. I've tried to use something like this https://stackoverflow.com/a/59113178 or directly using hotkeys.trigger() and determine is keyCode. But none of them worked. Is there any solution to determine the layout of a keyboard actually @Donorhan ?

### CODE REVIEW

**Comment by Donorhan** [comment]
To my knowledge there is no technique to detect the layout of a keyboard. There is `Keyboard.getLayoutMap()` but it doesn't return anything very interesting and it is experimental. In any case using `event.code` is the right way to not worry about the QWERTY/AZERTY configuration 👍🏻

**Comment by alimtunc** [comment]
> 

Yes sure, but the point was for the visual letter on keyboard haha

**Comment by Flowtter** [comment]
I think you could use [keyboard event](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)

Here is an example on an azerty keyboard:
image

And a qwerty one
image

**Comment by Donorhan** [comment]
@alimtunc I'm not sure I understand then, you want to display an image according the layout right?

**Comment by alimtunc** [comment]
> @alimtunc I'm not sure I understand then, you want to display an image according the layout right?

I want to display the correct letter on the direction step

**Comment by ramnes** [comment]
The easy fix could be to only display the arrows and let "advanced" users (i.e. people who played games in their life) realize that WASD / ZQSD also triggers the arrows. :)

**Comment by alimtunc** [comment]
@Donorhan @ramnes all is good

**Comment by Donorhan** [comment]
Thanks you!

**Pull request merged**
