### PR TITLE
feat: make the first user who register admin

### PR DESCRIPTION
**Pull request by riderx**
In order to make deployment of new lemverse easier, I propose to make the first user who register admin.

### CODE REVIEW

**Comment by DblK** [comment]
For your information, I like your PR but there is things to change.
You need to understand that there is two admin roles (I know it can be confusing 😛 )

So the first one allows you to run `remote` command and **HAVE to** be done inside the `settings.json` (for security reason) and then a new deploy.

The other one (inside mongo) is to allow `edition` in any lemverse.

Knowing that, can you do some adjustment in the documentation (I am okay with the code 😉 )?

**Comment by riderx** [comment]
@DblK okay i understand, i updated the doc

**Comment by DblK** [comment]
We are currently reviewing the solution has it might cause performance issue.
Will come back to you soon.

PS: Do not bother updating the PR for now.

**Comment by DblK** [comment]
I forgot this PR, I will do something pretty soon about it.

**Comment by DblK** [comment]
The base code has changed. Thanks for your contribution.
We have reported your changes in a slightly different way.

**Pull request closed without merging**
