### PR TITLE
EditorConfig

### PR DESCRIPTION
**Pull request by ramnes**
EditorConfig (https://editorconfig.org/) is quite the defacto standard for ensuring consistent contributions by configuring automatically contributors editors. :)

### CODE REVIEW

**Comment by Donorhan** [comment]
This is a good idea, thank you! Will you be able to resolve the conflicts?

**Comment by ramnes** [comment]
done :)

**Comment by ramnes** [comment]
PS – You need to merge this with a merge commit or the last commit will be useless. Or if you really don't want a merge commit, you can rebase/squash and then amend the last commit to put the right commit id.

**Comment by Donorhan** [comment]
Thank you!

**Pull request merged**
